// Auto-generated by bini-deploy - do not edit.
// Add routes by creating files in src/app/api/
// Generated at: 2026-07-28T07:56:37.440Z

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import _route0 from './src/app/api/hello.js';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/api', _route0);

// SPA fallback - serves index.html for all non-API, non-asset requests
app.get('*', async (c) => {
  const request = c.req.raw;
  const env = c.env;
  const assetResponse = await env.ASSETS.fetch(request);
  if (assetResponse.status === 200) {
    return assetResponse;
  }
  const indexHtml = await env.ASSETS.fetch(new URL('/index.html', request.url));
  return indexHtml;
});
export default app;
