// Auto-generated by bini-deploy - do not edit.
// Add routes by creating files in src/app/api/
// Generated at: 2026-08-27T05:36:55.964Z

import { Hono } from 'https://deno.land/x/hono@v4.3.11/mod.ts';
import { cors } from 'https://deno.land/x/hono@v4.3.11/middleware.ts';
import _route0 from '../src/app/api/hello.ts';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/api', _route0);

// Serve static files from dist (must come AFTER API routes)
app.get('/*', async (c) => {
  if (c.req.path.startsWith('/api/')) {
    return c.text('API route not found', 404);
  }
  const filePath = c.req.path === '/' ? '/index.html' : c.req.path;
  try {
    const file = await Deno.readFile(`./dist${filePath}`);
    const ext = filePath.split('.').pop();
    const contentType = {
      'html': 'text/html',
      'css': 'text/css',
      'js': 'application/javascript',
      'json': 'application/json',
      'png': 'image/png',
      'jpg': 'image/jpeg',
      'jpeg': 'image/jpeg'
    }[ext] || 'text/plain';
    return new Response(file, {
      headers: { 'Content-Type': contentType }
    });
  } catch {
    try {
      const indexHtml = await Deno.readFile('./dist/index.html');
      return new Response(indexHtml, {
        headers: { 'Content-Type': 'text/html' }
      });
    } catch {
      return c.text('File not found', 404);
    }
  }
});
Deno.serve({ port: Number(Deno.env.get('PORT') ?? 3000) }, app.fetch);
