// Auto-generated by bini-deploy - do not edit.
// Add routes by creating files in src/app/api/
// Generated at: 2026-08-27T06:31:19.042Z

import { Hono } from 'https://deno.land/x/hono@v4.3.11/mod.ts';
import { handle } from 'https://deno.land/x/hono@v4.3.11/adapter/netlify/index.ts';
import _route0 from '../../src/app/api/hello.ts';

const app = new Hono();
app.use('/api/*', async (c, next) => {
    await next();
    c.res.headers.set('Access-Control-Allow-Origin', '*');
    c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');
    c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization');
    if (c.req.method === 'OPTIONS') return new Response(null, { status: 204, headers: c.res.headers });
  });
app.route('/api', _route0);

export default handle(app);
