
     // @ts-nocheck
    // oxlint-disable
   // oxfmt-ignore
  // ⚠️  Auto-generated by bini-router — do not edit.

import React, { Suspense } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';

const Layout0 = React.lazy(() => import('@/app/layout'));
const Page0 = React.lazy(() => import('@/app/page'));

// ─── Error Boundary ───────────────────────────────────────────────────────────

class ErrorBoundary extends React.Component<
  { children: React.ReactNode },
  { error: Error | null }
> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    if (import.meta.env.DEV) {
      window.dispatchEvent(new CustomEvent('__bini_error__', {
        detail: { name: error.name, message: error.message, stack: error.stack, componentStack: errorInfo.componentStack, _type: 'runtime' }
      }));
    }
  }
  override render() {
    if (this.state.error) {
      if (import.meta.env.DEV) return null;
      return (
        <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui,sans-serif', padding: '2rem' }}>
          <div style={{ maxWidth: 480, width: '100%', textAlign: 'center' }}>
            <h2 style={{ color: '#e74c3c', marginBottom: '1rem' }}>Something went wrong</h2>
            <pre style={{ background: '#fef2f2', padding: '1rem', borderRadius: '0.5rem', textAlign: 'left', fontSize: '0.8rem', color: '#e74c3c', overflow: 'auto' }}>{this.state.error.toString()}</pre>
            <button onClick={() => this.setState({ error: null })} style={{ marginTop: '1rem', padding: '0.5rem 1.5rem', background: '#00CFFF', color: 'white', border: 'none', borderRadius: '0.5rem', cursor: 'pointer', fontWeight: 600 }}>
              Try again
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}


// Built-in Bini Router Loading Component
// Override by creating src/app/loading.tsx
function Spinner() {
  const [isDark, setIsDark] = React.useState(false);
  
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    
    return () => observer.disconnect();
  }, []);
  
  const styles = {
    root: {
      margin: 0,
      padding: 0,
      minHeight: '100vh',
      width: '100%',
    },
    container: {
      minHeight: '100vh',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#000000' : '#ffffff',
      margin: 0,
      padding: 0,
    },
    spinnerWrapper: {
      position: 'relative' as const,
      width: '3rem',
      height: '3rem',
    },
    outerRing: {
      position: 'absolute' as const,
      inset: 0,
      borderRadius: '9999px',
      border: '4px solid',
      borderColor: isDark ? '#262626' : '#e5e5e5',
    },
    spinningRing: {
      position: 'absolute' as const,
      inset: 0,
      borderRadius: '9999px',
      border: '4px solid',
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: '#06b6d4',
      animation: 'spin 0.8s linear infinite',
    },
  };
  
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.spinnerWrapper}>
          <div style={styles.outerRing} />
          <div style={styles.spinningRing} />
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        @keyframes spin {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }
      `}</style>
    </div>
  );
}


function TitleSetter({ title }: { title: string }) {
  React.useEffect(() => { document.title = title; }, [title]);
  return null;
}


// Built-in Bini Router 404 Page
// Override by creating src/app/not-found.tsx
function Default404() {
  const [isDark, setIsDark] = React.useState(false);
  
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    
    return () => observer.disconnect();
  }, []);
  
  const styles = {
    root: {
      margin: 0,
      padding: 0,
      minHeight: '100vh',
      width: '100%',
    },
    container: {
      minHeight: '100vh',
      width: '100%',
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center' as const,
      padding: '2rem',
      backgroundColor: isDark ? '#000000' : '#ffffff',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      margin: 0,
    },
    wrapper: {
      maxWidth: '42rem',
      margin: '0 auto',
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '1.5rem',
    },
    number: {
      fontSize: '8rem',
      fontWeight: 'bold',
      lineHeight: 1,
      letterSpacing: '-0.025em',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
      WebkitBackgroundClip: 'text',
      backgroundClip: 'text',
      color: 'transparent',
    },
    title: {
      fontSize: '1.5rem',
      fontWeight: 600,
      color: isDark ? '#ffffff' : '#000000',
    },
    message: {
      color: isDark ? '#a3a3a3' : '#737373',
      maxWidth: '28rem',
      margin: '0 auto',
    },
    button: {
      display: 'inline-block',
      padding: '0.75rem 2rem',
      borderRadius: '0.5rem',
      background: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
      color: 'white',
      textDecoration: 'none',
      fontSize: '0.875rem',
      fontWeight: 500,
      transition: 'opacity 0.2s',
      cursor: 'pointer',
      border: 'none',
    }
  };
  
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.wrapper}>
          <div style={styles.number}>404</div>
          <h1 style={styles.title}>Page not found</h1>
          <p style={styles.message}>
            The page you're looking for doesn't exist or has been moved.
          </p>
          <div>
            <a href="/" style={styles.button}>
              ← Back to home
            </a>
          </div>
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        a { text-decoration: none; }
      `}</style>
    </div>
  );
}

export default function App() {
  return (
    <BrowserRouter basename={"/"}>
      <Routes>
        <Route element={<><TitleSetter title={"Bini.js App"} /><Suspense fallback={<Spinner />}><ErrorBoundary><Layout0><Outlet /></Layout0></ErrorBoundary></Suspense></>}>
          <Route path="/" element={<Suspense fallback={<Spinner />}><ErrorBoundary><Page0 /></ErrorBoundary></Suspense>} />
        </Route>
        <Route path="*" element={<Default404 />} />
      </Routes>
    </BrowserRouter>
  );
}
