// @ts-nocheck
// oxlint-disable
// oxfmt-ignore
// ⚠️  Auto-generated by bini-router — do not edit.

import React, { Suspense } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';

const Layout0 = React.lazy(() => import('@/app/layout'));
const Page0 = React.lazy(() => import('@/app/page'));
const NotFound0 = React.lazy(() => import('@/app/not-found'));

// ─── Error Boundary ───────────────────────────────────────────────────────────

class ErrorBoundary extends React.Component<
  { children: React.ReactNode; fallback?: React.ComponentType<{ error: Error; reset: () => void }> },
  { error: Error | null }
> {
  constructor(props: { children: React.ReactNode; fallback?: React.ComponentType<{ error: Error; reset: () => void }> }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    if (import.meta.env.DEV) {
      window.dispatchEvent(new CustomEvent('__bini_error__', {
        detail: { name: error.name, message: error.message, stack: error.stack, componentStack: errorInfo.componentStack, _type: 'runtime' }
      }));
    }
  }
  override render() {
    if (this.state.error) {
      const reset = () => this.setState({ error: null });
      if (this.props.fallback) {
        const Fallback = this.props.fallback;
        return <Fallback error={this.state.error} reset={reset} />;
      }
      if (import.meta.env.DEV) return null;
      return (
        <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui,sans-serif', padding: '2rem' }}>
          <div style={{ maxWidth: 480, width: '100%', textAlign: 'center' }}>
            <h2 style={{ color: '#e74c3c', marginBottom: '1rem' }}>Something went wrong</h2>
            <pre style={{ background: '#fef2f2', padding: '1rem', borderRadius: '0.5rem', textAlign: 'left', fontSize: '0.8rem', color: '#e74c3c', overflow: 'auto' }}>{this.state.error.toString()}</pre>
            <button onClick={reset} style={{ marginTop: '1rem', padding: '0.5rem 1.5rem', background: '#00CFFF', color: 'white', border: 'none', borderRadius: '0.5rem', cursor: 'pointer', fontWeight: 600 }}>
              Try again
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}


function Spinner() {
  const [isDark, setIsDark] = React.useState(false);
  
  React.useEffect(() => {
    const isDarkMode = document.documentElement.classList.contains('dark') ||
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    setIsDark(isDarkMode);
    
    const observer = new MutationObserver(() => {
      setIsDark(document.documentElement.classList.contains('dark'));
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    
    return () => observer.disconnect();
  }, []);
  
  const styles = {
    root: { margin: 0, padding: 0, minHeight: '100vh', width: '100%' },
    container: {
      minHeight: '100vh',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#000000' : '#ffffff',
      margin: 0,
      padding: 0,
    },
    spinnerWrapper: { position: 'relative' as const, width: '3rem', height: '3rem' },
    outerRing: {
      position: 'absolute' as const,
      inset: 0,
      borderRadius: '9999px',
      border: '4px solid',
      borderColor: isDark ? '#262626' : '#e5e5e5',
    },
    spinningRing: {
      position: 'absolute' as const,
      inset: 0,
      borderRadius: '9999px',
      border: '4px solid',
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: '#06b6d4',
      animation: 'spin 0.8s linear infinite',
    },
  };
  
  return (
    <div style={styles.root}>
      <div style={styles.container}>
        <div style={styles.spinnerWrapper}>
          <div style={styles.outerRing} />
          <div style={styles.spinningRing} />
        </div>
      </div>
      <style>{`
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}


function TitleSetter({ title }: { title: string }) {
  React.useEffect(() => {
    if (typeof document !== 'undefined') {
      document.title = title;
    }
  }, [title]);
  return null;
}



export function AppRoutes() {
  return (
    <Routes>
        <Route element={<><TitleSetter title={"Bini.js App"} /><Suspense fallback={<Spinner />}><ErrorBoundary><Layout0><Outlet /></Layout0></ErrorBoundary></Suspense></>}>
          <Route path="/" element={<Suspense fallback={<Spinner />}><ErrorBoundary><Page0 /></ErrorBoundary></Suspense>} />
        </Route>
        <Route path="*" element={          <><TitleSetter title={"Bini.js App"} /><Layout0>            <Suspense fallback={<Spinner />}><ErrorBoundary><NotFound0 /></ErrorBoundary></Suspense></Layout0></>} />
    </Routes>
  );
}

export const basename = "/";

export default function App() {
  return (
    <BrowserRouter basename={basename}>
      <AppRoutes />
    </BrowserRouter>
  );
}
