// Auto-generated by bini-deploy - do not edit.
// Add routes by creating files in src/app/api/
// Generated at: 2026-07-28T00:27:00.253Z

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import _route0 from '../src/app/api/hello';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/api', _route0);

export default app.fetch;
